version: '3'

services:
    php-env:
        depends_on:
            - trying_db
        build: .
        ports:
            - "9000:8000"
        volumes:
            - ./trying:/var/www/html

    mailer:
        image: schickling/mailcatcher
        ports: [ "1025", "1080" ]

    trying_db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - trying_db_data:/var/lib/mysql
        ports:
            - "3306:3306"


    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - trying_db
        restart: always
        ports:
            - "9002:80"
        environment:
            - PMA_ARBITRARY=1

volumes:
    trying_db_data: {}
